### ISSUE TITLE
can you provide caddy v1.0.5?

### ISSUE THREAD

**Issue by U201413497** [zedifen/build-naive-caddy#1]
Caddy v2 is more complicated to set up multiple users. The latest version of caddy v1 is 1.0.5. Can you provide the 1.0.5 version?

**Comment by zedifen** [comment]
Multiauth support is added back via `https://github.com/caddyserver/forwardproxy/pull/99` and [configuration](https://github.com/caddyserver/forwardproxy/pull/99) is rather simple. Also forwardproxy upstream dropped caddy v1 support.

Related: https://github.com/klzgrad/naiveproxy/issues/556.
